# Form implementation generated from reading ui file 'GUITest2.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widget.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.widget.setObjectName("widget")
        self.Foto2 = QtWidgets.QLabel(parent=self.widget)
        self.Foto2.setGeometry(QtCore.QRect(0, 350, 385, 385))
        self.Foto2.setText("")
        self.Foto2.setScaledContents(False)
        self.Foto2.setObjectName("Foto2")
        self.Foto3 = QtWidgets.QLabel(parent=self.widget)
        self.Foto3.setGeometry(QtCore.QRect(385, 350, 385, 385))
        self.Foto3.setText("")
        self.Foto3.setScaledContents(False)
        self.Foto3.setObjectName("Foto3")
        self.Foto4 = QtWidgets.QLabel(parent=self.widget)
        self.Foto4.setGeometry(QtCore.QRect(770, 350, 385, 385))
        self.Foto4.setText("")
        self.Foto4.setScaledContents(False)
        self.Foto4.setObjectName("Foto4")
        self.Foto5 = QtWidgets.QLabel(parent=self.widget)
        self.Foto5.setGeometry(QtCore.QRect(1155, 350, 385, 385))
        self.Foto5.setText("")
        self.Foto5.setObjectName("Foto5")
        self.Foto6 = QtWidgets.QLabel(parent=self.widget)
        self.Foto6.setGeometry(QtCore.QRect(1540, 350, 385, 385))
        self.Foto6.setText("")
        self.Foto6.setScaledContents(False)
        self.Foto6.setObjectName("Foto6")
        self.Foto1 = QtWidgets.QLabel(parent=self.widget)
        self.Foto1.setGeometry(QtCore.QRect(585, 165, 750, 750))
        self.Foto1.setText("")
        self.Foto1.setScaledContents(False)
        self.Foto1.setObjectName("Foto1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
